### PR TITLE
Webpack2 Upgrade

### PR DESCRIPTION
**Pull request by 3kynox**
Process to upgrade to Webpack2

### CODE REVIEW

**Comment by 3kynox** [comment]
WIP - Not ready yet.

Webpack2 migration tutorial page asks to tell Babel not to convert modules into CommonJS but once done, import syntax error is triggered.

**Comment by 3kynox** [comment]
All Modules import errors looks like related to path.join... values that are wrong, investigating.
Coming back for some more commits tonight.

**Comment by 3kynox** [comment]
At this point, here is the npm start command return : 

https://paste.ofcode.org/aeUFfpyEk9uVNzD3J4jSRX

... and npm run build : 

https://paste.ofcode.org/9RBfRAuuF8a2HK2jfm5cmC

As webpack2 do not need anymore that babel transpile code, I have to find a way to manage experimental (stage-0) code. Once done, it will get rid of errors shown above like : 

- this[event.method] = ::this[event.method];
-    ...global

And for more npm start related errors, it's look like again related to a path issue.

**Comment by 3kynox** [comment]
Ready for merge after owner checking.
Going to VueJS2.0 after that.

**Comment by patrickheng** [comment]
Amazing work ! Thanks @3kynox

**Comment by 3kynox** [comment]
yvw :)

**Pull request merged**
